# Generated by Django 4.1.6 on 2023-02-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Для страницы')),
                ('price', models.CharField(max_length=150, verbose_name='Стоимость мероприятия')),
                ('akciya1_title', models.CharField(max_length=150, verbose_name='Название акции_1')),
                ('akciya2_title', models.CharField(max_length=150, verbose_name='Название акции_2')),
                ('akciya3_title', models.CharField(max_length=150, verbose_name='Название акции_3')),
                ('akciya1_desc', models.CharField(max_length=150, verbose_name='Описание акции_1')),
                ('akciya2_desc', models.CharField(max_length=150, verbose_name='Описание акции_2')),
                ('akciya3_desc', models.CharField(max_length=150, verbose_name='Описание акции_3')),
                ('happy_package_quota', models.CharField(max_length=150, verbose_name='для скольки человек')),
                ('happy_package_price', models.CharField(max_length=150, verbose_name='Стоимость предложения')),
                ('happy_package', models.TextField(blank=True, verbose_name='Предложение ресторана')),
            ],
            options={
                'verbose_name': 'Страница - День рождения',
                'verbose_name_plural': 'Страницы - День рождения',
            },
        ),
    ]
