# Generated by Django 4.1.6 on 2023-02-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menurest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='для страницы')),
                ('wine', models.TextField(blank=True, verbose_name='wine')),
                ('wine_bar', models.TextField(blank=True, verbose_name='wine_bar')),
                ('bar', models.TextField(blank=True, verbose_name='bar')),
                ('menu', models.TextField(blank=True, verbose_name='menu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Меню ресторана',
                'verbose_name_plural': 'Меню ресторана',
            },
        ),
    ]
