# Generated by Django 4.1.6 on 2023-02-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menurest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menurest',
            options={'verbose_name': 'Опции меню ресторана', 'verbose_name_plural': 'Опции меню ресторана'},
        ),
    ]
