# Generated by Django 4.1.6 on 2023-02-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Для страницы')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=150, verbose_name='Электронная почта')),
                ('time1', models.CharField(max_length=150, verbose_name='Время1')),
                ('time2', models.CharField(max_length=150, verbose_name='Время2')),
                ('time3', models.CharField(max_length=150, verbose_name='Время3')),
                ('content', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
