# Generated by Django 4.1.6 on 2023-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(default=1, max_length=150, verbose_name='Ссылка на Telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='vk',
            field=models.CharField(default=1, max_length=150, verbose_name='Ссылка на VK'),
            preserve_default=False,
        ),
    ]
