# Generated by Django 4.1.6 on 2023-02-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_telegram_contacts_vk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
