# Generated by Django 4.1.6 on 2023-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Опция меню', 'verbose_name_plural': 'Опции меню'},
        ),
        migrations.RemoveField(
            model_name='menus',
            name='slug',
        ),
        migrations.AlterField(
            model_name='menus',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Актуально да/нет'),
        ),
    ]
