# Generated by Django 4.1.6 on 2023-02-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_category_options_alter_menus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'Подкатегория меню', 'verbose_name_plural': 'Подкатегории меню'},
        ),
    ]
