# Generated by Django 4.1.6 on 2023-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degustation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Для страницы')),
                ('date', models.CharField(max_length=150, verbose_name='Дата и время')),
                ('price', models.CharField(max_length=150, verbose_name='Стоимость мероприятия')),
                ('content', models.TextField(blank=True, verbose_name='Описание мероприятия')),
            ],
            options={
                'verbose_name': 'Страница - Дегустационный винный вечер',
                'verbose_name_plural': 'Страницы - Дегустационный винный вечер',
            },
        ),
    ]
