# Generated by Django 4.1.6 on 2023-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='og_description',
            field=models.CharField(default=1, max_length=500, verbose_name='Facebook og:description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='og_title',
            field=models.CharField(default=1, max_length=500, verbose_name='Facebook og:title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='og_type',
            field=models.CharField(default=1, max_length=500, verbose_name='Facebook og:type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='title_page',
            field=models.CharField(default=1, max_length=500, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='twitter_card',
            field=models.CharField(default=1, max_length=500, verbose_name='twitter:card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='twitter_creator',
            field=models.CharField(default=1, max_length=500, verbose_name='twitter:creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='twitter_description',
            field=models.CharField(default=1, max_length=500, verbose_name='twitter:description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='twitter_title',
            field=models.CharField(default=1, max_length=500, verbose_name='twitter:title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(max_length=350, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='keywords',
            field=models.CharField(max_length=350, verbose_name='keywords'),
        ),
    ]
