# Generated by Django 4.1.6 on 2023-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_og_description_articles_og_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='og_description',
            field=models.TextField(verbose_name='Facebook og:description'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='twitter_description',
            field=models.TextField(verbose_name='twitter:description'),
        ),
    ]
