# Generated by Django 4.1.6 on 2023-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_og_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='keywords',
            field=models.TextField(verbose_name='keywords'),
        ),
    ]
