# Generated by Django 4.1.6 on 2023-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articles_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='og_title',
            field=models.TextField(verbose_name='Facebook og:title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title_page',
            field=models.TextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='twitter_title',
            field=models.TextField(verbose_name='twitter:title'),
        ),
    ]
