# Generated by Django 4.1.6 on 2023-02-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='dateReview',
            field=models.CharField(default=1, max_length=150, verbose_name='Дата отзыва'),
            preserve_default=False,
        ),
    ]
