# Generated by Django 4.1.6 on 2023-02-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polytics',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
