# Generated by Django 4.1.6 on 2023-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Для страницы')),
                ('title_page', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('keywords', models.CharField(max_length=500, verbose_name='keywords')),
                ('og_type', models.CharField(max_length=500, verbose_name='Facebook og:type')),
                ('og_title', models.CharField(max_length=500, verbose_name='Facebook og:title')),
                ('og_description', models.CharField(max_length=500, verbose_name='Facebook og:description')),
                ('twitter_creator', models.CharField(max_length=500, verbose_name='twitter:creator')),
                ('twitter_card', models.CharField(max_length=500, verbose_name='twitter:card')),
                ('twitter_title', models.CharField(max_length=500, verbose_name='twitter:title')),
                ('twitter_description', models.CharField(max_length=500, verbose_name='twitter:description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оптимизации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'SEO оптимизация',
                'verbose_name_plural': 'SEO оптимизация',
            },
        ),
    ]
