# Generated by Django 4.1.6 on 2023-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_seo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='og_description',
            field=models.TextField(verbose_name='Facebook og:description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_description',
            field=models.TextField(verbose_name='twitter:description'),
        ),
    ]
