# Generated by Django 4.1.6 on 2023-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_seo_og_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.TextField(verbose_name='keywords'),
        ),
    ]
