# Generated by Django 4.1.6 on 2023-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_alter_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='title_page',
            field=models.TextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_title',
            field=models.TextField(verbose_name='twitter:title'),
        ),
    ]
