# Generated by Django 4.1.6 on 2023-02-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_alter_seo_title_page_alter_seo_twitter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='og_title',
            field=models.TextField(verbose_name='Facebook og:title'),
        ),
    ]
