# Generated by Django 4.1.6 on 2023-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название распродажи')),
                ('contentSale', models.TextField(blank=True, verbose_name='Описание акции')),
                ('contentPopup', models.TextField(blank=True, verbose_name='Описание подробностей акции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Баннер')),
                ('is_published', models.BooleanField(default=True, verbose_name='Размещено да/нет')),
                ('itemSale1', models.CharField(max_length=150, verbose_name='Верхнее описание')),
                ('itemSale2', models.CharField(max_length=150, verbose_name='Нижнее описание')),
                ('discount', models.CharField(max_length=150, verbose_name='Описание скидки')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
