# Generated by Django 4.1.6 on 2023-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormsReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарии к заказу')),
                ('dateReserve', models.CharField(max_length=150, verbose_name='Желаемая дата')),
                ('timeReserve', models.CharField(max_length=150, verbose_name='Желаемое время')),
                ('quantity', models.CharField(max_length=150, verbose_name='Количество гостей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления заказа')),
            ],
            options={
                'verbose_name': 'Резервирование столика',
                'verbose_name_plural': 'Резервирование столиков',
            },
        ),
    ]
