# Generated by Django 4.1.6 on 2023-02-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formsreservedegustation_formsreservehappy'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsreservedegustation',
            name='note',
            field=models.CharField(default=1, max_length=150, verbose_name='Примечание к заказу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsreservehappy',
            name='note',
            field=models.CharField(default=1, max_length=150, verbose_name='Примечание к заказу'),
            preserve_default=False,
        ),
    ]
